/// <reference path="../../node_modules/graphschematojson/src/types.d.ts"/>
import { lowerFirst } from './query'
import { getIdKey, getId, getEntities } from '../entity'
import * as consts from '../consts'

/**
 * 
 * @param {Field} field 
 * @return {string}
 */
export const fieldType = (field) =>
    `${field.isList ? '[' : ''}${field.type}${field.isList ? ']' : ''}`
/**
 * @function
 * @param {Field} field
 * @return {boolean}
 */
export const isAutoGenerated = (field) => field.directives[consts.PRIMARY_GENERATED_COLUMN] ? true : false
/**
 * @function
 * @param {Field} field 
 * @param {boolean} create
 * @return {boolean}
 */
export const isRequired = (field, create = true) => {
    if (isAutoGenerated(field)) {
        return false
    }
    if (!field.isNullable && create) {
        return true
    }
    return false
}
/**
 * @function
 * @param {Field} field 
 * @param {boolean} create 
 * @return {string}
 */
export const fieldRequired = (field, create = true) => isRequired(field, create) ? '!' : ''

/**
 * @function
 * @param {string} name 
 * @param {Field} field
 * @param {boolean} create
 * @return {string}
 */
export const createMutationInputField = (name, field, create = true) => 
    `    ${name}: ${fieldType(field)}${fieldRequired(field, create)}`

/**
 * @function
 * @param {string} name 
 * @param {Object.<string, Type | Enum>} types
 * @return {string}
 */
export const createMutationInputs = (name, types) =>

`
type Create${name}Input {
${Object.keys(types[name].fields)
    .filter(fieldKey => !isAutoGenerated(types[name].fields[fieldKey]))
    .map(fieldKey =>
        createMutationInputField(fieldKey, types[name].fields[fieldKey])).join('\n')
}
}`

/**
 * @function
 * @param {string} name 
 * @param {Object.<string, Type | Enum>} types 
 * @return {string}
 */
export const updateMutationInputs = (name, types) =>

`
type Update${name}Input {
${Object.keys(types[name].fields)
    .map(fieldKey => createMutationInputField(fieldKey, types[name].fields[fieldKey], false)).join('\n')
}
}`

/**
 * @function
 * @param {string} name 
 * @param {Type} model 
 * @return {string}
 */
export const createMutation = (name, model) =>

`
    create${name}(data: Create${name}Input): ${name}
    update${name}(data: Update${name}Input): ${name}`


export default (/** @type {Object.<string, Type | Enum>} */types) =>

`
${Object.keys(getEntities(types)).map(typeKey => createMutationInputs(typeKey, types)).join('\n')}
${Object.keys(getEntities(types)).map(typeKey => updateMutationInputs(typeKey, types)).join('\n')}

type mutation {
${Object.keys(getEntities(types))
    .map(typeKey =>
        createMutation(
            typeKey,
            /** @type {Type} */(types[typeKey])
        )
    ).join('\n')
}
}
`